import Head from 'next/head'
import Header from "../components/Header";
import Navbar from "../components/Nav";
import Results from "../components/Results";
import apiSettings, { API_URL } from "../utils/request";

export default function Home({results}) {
  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps (context){
  const genre = context.query.genre;
  const request =
    await fetch(
      `${API_URL}${apiSettings[genre]?.url || apiSettings.fetchTrending.url}`
    ).then((response) => response.json())
   ;

  return {
    props: {
      results: request.results,
    },
  };
};